### ISSUE TITLE
Complain about "Non-Free Javascript" on your website

### ISSUE THREAD

**Issue by eglefino** [bbondy/codefirefox#262]
Dear Sir/Miss,

Sorry I have this to say, but I complain because the GNU.org complain about this. I have a Firefox add-on in my browser from GNU.org named libreJS, which analyse every website I visit. I will place here my manual of the libreJS, what it does what I may do (to help) a.s.o.
Sorry, it's not something to make you mad at me, but get the World Wide Web cleaner and up-to-date (I think).
The documentation [pdf] of the GNU.org is 30 pages:
https://www.gnu.org/software/librejs/manual/librejs.pdf

Hope you understand why I give a comment [complain],

Kindly regards,
Eglefino

**Comment by bbondy** [comment]
Sorry, what do you want me to change?

**Comment by bbondy** [comment]
I think maybe you mean Google analytics, just install an adblock if you don't want that.

**Comment by eglefino** [comment]
My complain-message to you was and is an order of the GNU-organisation [written by me] to warn you on a 'pretty way' that  by the (IMO crazy) copyright laws of the US-government, all used Java[scripts] and other used software products designed in your website MUST be made by [free] open source products, so in this example you have to use free Javascript products and otherwise chance it to free javascripts products, because the US-copyright laws will tell you in future time...."You get a penalty and your website will go offline !! because of the use  of a commercial copyrighted product in your website.... !!!

The GNU.org searched for volunteers to help them with this volunteer-work to tell this story to other persons, so the whole story will go by a fast chain. And you was my first warn/person..... which didn't understand my 'pretty message' ... in my first short message. 

In this whole story I'm only a middleman/volunteer working unpaid for the GNU.org and tell others this (IMO crazy) copyright story of the GNU.org I ever heart for. The GNU will warn every-one who used commercial copyrighted products in their life. Maybe you and others can find free time to chance the copyright products in copyleft/free open source products.... before the penalty take place.

I hope you can understand my 'pretty message' now?

I used the word complain only 'so you will read this message', it was an idea of the GNU to use the word complain in the message. By the way, I stopped after your answer with my volunteer work for the GNU.org, because this carry on takes to much energy of me, which I can use better.

Kindly regards,
Eglefino

P.S.:
I'm open, honest and sincere to myself, to my partner and with some reticent also to strangers, as bedridden and disabled person (since 2006) I even want to respect others, as they will respect me....!
