### ISSUE TITLE
start msvc11 missing

### ISSUE THREAD

**Issue by RomanADavis** [bbondy/codefirefox#263]
From here:

http://codefirefox.com/video/get-source-code

I  think your videos at codefirefox videos are outdated. All I've got is start shell msvc 2013 and 2015.

**Comment by bbondy** [comment]
I added a comment that it's out of date and to use the newer scripts.  I don't think I'll have time to redo the outdated videos so adding comments is best for now. If it becomes confusing then I can just close out the site or put a warning about it being out of date.
